apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr3-vllm-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr3-vllm-1
  name: apr3-vllm-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
