apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr3-vllm-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr3-vllm-1
  name: apr3-vllm-1
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: apr3-vllm-1
